name: Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Install JS deps
        run: |
          task js:install
      - name: Build JS
        run: |
          task js:build
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Python deps
        run: |
          pip install -r requirements-dev.lock
      - name: Install Hatch
        run: |
          pip install --upgrade hatch
      - name: Build package
        run: |
          hatch build
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/*"
